DELETE http://localhost:3001/api/houses/64909c97293d6700147f01fe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOTI3ZDAzNGI2MmY0MGMzODExZjYwZiIsInVzZXJuYW1lIjoiYWRtaW4xMjM0NSIsImlhdCI6MTY4NzE5ODE2MCwiZXhwIjoxNjg3ODAyOTYwfQ.0w6mQCE1iZDa_fO6lutW2NkxGxfEX0cOVs7JVcEEm_w
