PUT http://localhost:3001/api/houses/649098c3c34a070014a9323d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOTI3ZDAzNGI2MmY0MGMzODExZjYwZiIsInVzZXJuYW1lIjoiYWRtaW4xMjM0NSIsImlhdCI6MTY4NzE5ODA3NCwiZXhwIjoxNjg3ODAyODc0fQ.Rpu57rJPM1P-etGSUiVuIElVyLYYmotzhgu0w-Yo16Y

{
  "operation": "rent",
  "price": 2000,
  "country": "España",
  "region": "Cataluña",
  "city": "Barcelona",
  "neighborhood": "Eixample",
  "postalCode": "08015",
  "street": "Carrer de Viladomat",
  "addressNumber": "229",
  "floor": "2",
  "door": "1",
  "stair": "A",
  "propertyType": "apartment",
  "rooms": 4,
  "bathrooms": 2,
  "size": 100,
  "floors": 6,
  "heatingCooling": "central",
  "water": true,
  "electricity": true,
  "gas": true,
  "furnished": true,
  "pets": false,
  "parkingIncluded": false,
  "parkingOptional": true,
  "parkingPrice": 100,
  "pool": false,
  "jacuzzi": false,
  "garden": false,
  "terrace": false,
  "horizontal": false,
  "exterior": true,
  "elevator": true,
  "constructionYear": "2000-01-01",
  "renovationYear": "2020-04-01",
  "antiquity": 21,
  "observations": "Lala la",
  "ownerName": "Maria Lopez",
  "ownerPhone": "654987123",
  "ownerEmail": "maria.lopez@example.com",
  "title": "Alquiler de Piso en calle de Viladomat",
  "description": "Piso en alquiler en calle de Viladomat, Barcelona, Barcelona, España.",
  "address": "Carrer de Viladomat, 209, Barcelona, Spain",
  "lat": 41.383235,
  "lng": 2.157475,
  "isAddress": true,
  "exactPosition": true,
  "showInMap": true,
  "photos": [],
  "videos": [],
  "documents": []
}
